name: CI

on: [push]
  # push:
  #   branches: 
  #     - main
  #     - feature/xx

jobs: 
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code # Checkout Code 
        uses: actions/checkout@v2

      - name: Setup Python # Setup Python using Action - Setup-Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8

      - name: Install Bandit # Intall Bandit on the Ubuntu machine using a command
        run: pip install bandit 

      - name: Run Bandit Scan # Run bandit in recursive mode to scan all files in app code. Output bandit report file
        run: bandit -ll -ii -r . -f json -o bandit-report.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always() # this indicates to always run this step; failed steps stop processing, but a vuln scan will fail by design when finding vulns.  Set if: always() to always run this step regardless of previous results
        with:
          name: bandit-findings
          path: bandit-report.json
          
